# Generated by Django 5.2.14 on 2026-06-24 04:52

import django.db.models.deletion
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1234_oauthapplication_optional_scopes_and_more"),
        ("web_analytics", "0004_rename_achievement_track_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAnalyticsPathCleaningSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="suggested",
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("suggested_rules", models.JSONField(default=list)),
                ("sampled_path_count", models.IntegerField(default=0)),
                ("distinct_path_count", models.IntegerField(default=0)),
                ("existing_rule_count", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team"),
                ),
            ],
            options={
                "db_table": "posthog_webanalyticspathcleaningsuggestion",
                "indexes": [models.Index(fields=["team", "-created_at"], name="wa_pcs_team_created_idx")],
            },
        ),
    ]
