from products.web_analytics.backend.temporal.digest_notification import (
    ACTIVITIES as DIGEST_NOTIFICATION_ACTIVITIES,
    WORKFLOWS as DIGEST_NOTIFICATION_WORKFLOWS,
)
from products.web_analytics.backend.temporal.path_cleaning_suggestions import (
    ACTIVITIES as PATH_CLEANING_ACTIVITIES,
    WORKFLOWS as PATH_CLEANING_WORKFLOWS,
)
from products.web_analytics.backend.temporal.weekly_digest import (
    ACTIVITIES as WEEKLY_DIGEST_ACTIVITIES,
    WORKFLOWS as WEEKLY_DIGEST_WORKFLOWS,
)

WORKFLOWS = WEEKLY_DIGEST_WORKFLOWS + DIGEST_NOTIFICATION_WORKFLOWS + PATH_CLEANING_WORKFLOWS
ACTIVITIES = WEEKLY_DIGEST_ACTIVITIES + DIGEST_NOTIFICATION_ACTIVITIES + PATH_CLEANING_ACTIVITIES
